SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE  VIEW [bds].[RE_CONTRATOS]
AS
SELECT SOCIEDAD,
       NIF,
       CONTRATO,
       DEN_CONTRATO,
       VIGCONTRATO,
       NOMCOMERCIAL,
       OBJALQUILER,
       GAFO,
       SUBGAFO
  FROM ods.RE_CONTRATOS
 WHERE ORDINTERLOCCOMERCIAL = 1
GO