SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [ods].[SRVCOM_OPERADORES_CONTRATOS]
AS
SELECT
  so.RUCEMISOR
 ,so.CODIGOMALL AS LOCACION_COD
 ,lo.AZU_DESC_MED AS LOCACION_DESC
 ,so.CODIGOTIENDA AS TIENDA_COD
 ,so.CONTRATO_RE
 ,rc.DEN_CONTRATO AS DENCONTRATO
 ,rc.NOMCOMERCIAL
 ,rc.OBJALQUILER
 ,rc.INI_CONTRATO_MOD AS CONTRATO_FECINI
 ,rc.FIN_CONTRATO_MOD AS CONTRATO_FECFIN
 ,rc.VIGCONTRATO
 ,rc.GAFO
 ,rc.SUBGAFO
FROM ods.SRVCOM_OPERADORES so
LEFT JOIN ini.LYTY_ASOCIADO lo
  ON so.CODIGOMALL = lo.AZU_IDGRCO
LEFT JOIN bds.RE_CONTRATOS rc
  ON so.RUCEMISOR = rc.NIF
    AND so.CONTRATO_RE = rc.CONTRATO
    AND lo.SAP_SOC = rc.SOCIEDAD
WHERE rc.ORDINTERLOCCOMERCIAL = 1
GO