CREATE TABLE [bds].[SRVLYTY_or] (
  [srv_ID] [varchar](30) NULL,
  [srv_NOMBRE] [varchar](50) NULL,
  [srv_RAZONSOCIAL] [varchar](50) NULL,
  [srv_NOMBRETIENDA] [varchar](50) NULL,
  [srv_NOMBRETIENDA_ID] [varchar](255) NOT NULL,
  [srv_CODIGOLOCACION] [varchar](2) NULL,
  [srv_CODIGOLOCACION_D] [varchar](150) NULL,
  [srv_CODIGOTIENDA] [varchar](4) NULL,
  [srv_RUCEMISOR] [varchar](11) NULL,
  [srv_NUMEROTERMINAL] [varchar](10) NULL,
  [srv_SERIE] [varchar](10) NULL,
  [srv_TIPOTRANSACCION] [varchar](4) NULL,
  [srv_NUMEROTRANSACCION] [varchar](10) NULL,
  [FECHA_ID] [varchar](20) NULL,
  [srv_HORA] [varchar](8) NULL,
  [srv_HORAHH] [varchar](2) NULL,
  [srv_HORAMI] [varchar](2) NULL,
  [srv_HORA_RANGO] [varchar](20) NULL,
  [srv_VENDEDOR] [varchar](20) NULL,
  [srv_DNI] [varchar](11) NULL,
  [srv_RUC] [varchar](11) NULL,
  [srv_CE] [varchar](11) NULL,
  [srv_DUIval] [varchar](1) NULL,
  [srv_DUI] [varchar](11) NULL,
  [srv_DUITIPO] [varchar](3) NULL,
  [srv_NOMBRECLIENTE] [varchar](100) NULL,
  [srv_DIRECCIONCLIENTE] [varchar](200) NULL,
  [srv_BONUS] [varchar](20) NULL,
  [srv_MONEDA] [varchar](10) NULL,
  [srv_MEDIOPAGO] [varchar](10) NULL,
  [srv_TOTVALORVTABRUTA] [decimal](18, 2) NULL,
  [srv_DESCUENTOSGLOBAL] [decimal](18, 2) NULL,
  [srv_MONTOTOTALIGV] [decimal](18, 2) NULL,
  [srv_TOTVALORVENTANETA] [decimal](18, 2) NULL,
  [srv_ORDENITEM] [varchar](20) NULL,
  [srv_CANTUNIDADESITEM] [decimal](18, 2) NULL,
  [srv_CODIGOPRODUCTO] [varchar](50) NULL,
  [srv_DESCRIPCIONPROD] [varchar](100) NULL,
  [srv_PRECIOVTAUNITITEM] [decimal](18, 2) NULL,
  [srv_CARGODESCUENTOITEM] [decimal](18, 2) NULL,
  [srv_PRECIOTOTALITEM] [decimal](18, 2) NULL,
  [lty_CODIGOPERSONA] [varchar](10) NULL,
  [lty_ORDTARJETABONUS] [int] NULL,
  [lty_NUMTARJETABONUS] [varchar](19) NULL,
  [lty_TIPOTARJETA] [varchar](20) NULL,
  [lty_CODTIPOPERSONA] [varchar](2) NULL,
  [lty_CODTIPOPERSONA_D] [varchar](8) NULL,
  [lty_TIPODEDOCUMENTO] [varchar](4) NULL,
  [lty_TIPODEDOCUMENTO_D] [varchar](11) NULL,
  [lty_NRODOCUMENTO] [varchar](15) NULL,
  [lty_NRORUC] [varchar](11) NULL,
  [lty_NOMBRES] [varchar](100) NULL,
  [lty_APELLIDOPATERNO] [varchar](50) NULL,
  [lty_APELLIDOMATERNO] [varchar](50) NULL,
  [lty_FECHANACIMIENTO] [varchar](8) NULL,
  [lty_EDAD] [int] NULL,
  [lty_EDAD_RANGO] [varchar](13) NULL,
  [lty_SEXO_TIT_D] [varchar](11) NULL,
  [lty_F_ESTADOCIVIL_D] [varchar](11) NULL,
  [lty_F_COMPARTEDATOS_D] [varchar](2) NULL,
  [lty_F_AUTCANJE_D] [varchar](2) NULL,
  [lty_F_CLTEFALLECIDO_D] [varchar](2) NULL,
  [lty_RAZONSOCIAL] [varchar](50) NULL,
  [lty_CODPOS] [varchar](6) NULL,
  [lty_DIRECCION] [varchar](150) NULL,
  [lty_DEPARTAMENTO] [varchar](25) NULL,
  [lty_PROVINCIA] [varchar](25) NULL,
  [lty_DISTRITO] [varchar](25) NULL,
  [lty_DISTRITO_ID] [varchar](77) NULL,
  [lty_REFERENCIA] [varchar](150) NULL,
  [lty_ESTADO] [varchar](1) NULL,
  [lty_ESTADO_D] [varchar](6) NULL,
  [lty_COORDENADAX] [varchar](20) NULL,
  [lty_COORDENADAY] [varchar](20) NULL,
  [lty_NSE] [varchar](1) NULL,
  [lty_TELEFONO] [varchar](10) NULL,
  [lty_TELEFONO_D] [varchar](10) NULL,
  [lty_EMAIL] [varchar](100) NULL,
  [lty_HIJ_AS] [int] NULL,
  [lty_HIJ_OS] [int] NULL,
  [lty_HIJ_NN] [int] NULL,
  [com_TipoNegocio] [varchar](16) NULL,
  [com_ContratoRE] [varchar](10) NULL,
  [com_denContrato] [varchar](100) NULL,
  [com_VigContrato] [varchar](50) NULL,
  [com_NomComercial] [varchar](100) NULL,
  [com_ObjAlquiler] [varchar](100) NULL,
  [com_Gafo] [varchar](100) NULL,
  [com_SubGafo] [varchar](100) NULL
)
ON [PRIMARY]
GO